# Exercices NumPy 

<span style="color:red">Réalisation de tous les exercices sans utiliser de boucles.</span>
---

In [1]:
import numpy as np

# Configuration de la précision d'affichage
np.set_printoptions(precision=2, suppress=True)
print("NumPy version:", np.__version__)

NumPy version: 2.5.3


## Exercice 1 : Création et restructuration d'un tableau (1D → 2D)

**Objectif :**
1. Créez un vecteur 1D contenant les entiers de 1 à 20.
2. Transformez-le en une matrice 2D de dimensions $4 \times 5$.

In [5]:
# VOTRE CODE ICI

# 1D
a = np.arange(20)
print(a)

# 2D
a = a.reshape(4,5)
print(a)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


## Exercice 2 : Extraction par masque booléen (1D)

**Objectif :**
Soit un vecteur 1D de 15 nombres aléatoires entre 0 et 50. Extrayez tous les éléments strictement supérieurs à 25 **ET** pairs.

In [ ]:

# VOTRE CODE ICI

a = np.random.randint(0,50,15)
print(a)

print((a>25) & (a%2 ==0)) # return array of boolean values

# Extract
result = a[(a>25) & (a%2 ==0)]

print(result)






[ 5 36 25 39 33 13 43  9  5 33  3 46 21 38 24]
[False  True False False False False False False False False False  True
 False  True False]
[36 46 38]


## Exercice 3 : Inversion et inversion par colonnes (1D et 2D)

**Objectif :**
1. Inversez l'ordre des éléments d'un vecteur 1D de taille 10.
2. Soit une matrice $4 \times 4$, inversez l'ordre de ses colonnes (la dernière colonne devient la première).

In [ ]:
# VOTRE CODE ICI
a = np.random.randint(0,100,10)

print(a)

# Inverse
inverse = a[::-1]
print(inverse)


# Inverse Colonnes
a = np.random.randint(0,100,16).reshape(4,4)
print(a)
inverse_colonnes = a[:,::-1]

print(inverse_colonnes)





[ 8 37 87 57 49 80 61 89 38 64]
[64 38 89 61 80 49 57 87 37  8]
[[14 38 49  7]
 [89 83 24 79]
 [98 56 36 39]
 [33 65 50  5]]
[[ 7 49 38 14]
 [79 24 83 89]
 [39 36 56 98]
 [ 5 50 65 33]]


## Exercice 4 : Statistique par axe (2D)

**Objectif :**
Soit une matrice $5 \times 3$ d'entiers aléatoires entre 1 et 100.
1. Calculez la moyenne globale de la matrice.
2. Calculez la somme des éléments pour chaque **colonne**.
3. Obtenez la valeur maximale pour chaque **ligne**.

In [19]:
# VOTRE CODE ICI

matrice = np.random.randint(1,100,15).reshape(5,3)
print(matrice)

moyen = matrice.mean()
print(f"moyen: {moyen}")
somme_colonne = np.sum(matrice,axis=0)
print(f"somme_colonnes:\n {somme_colonne}")

max_lines = np.max(matrice,axis=1)
print(f"max_lines:\n {max_lines}")



[[73 29 81]
 [96 87 67]
 [ 7 90 17]
 [80 73 29]
 [21  6 37]]
moyen: 52.86666666666667
somme_colonnes:
 [277 285 231]
max_lines:
 [81 96 90 80 37]


## Exercice 5 : Remplacement des valeurs manquantes (1D / 2D)

**Objectif :**
Soit le tableau : `arr = np.array([1.0, 2.0, np.nan, 4.0, np.nan, 6.0])`.
Remplacez toutes les valeurs `NaN` par la moyenne des valeurs non manquantes du tableau.

In [ ]:
# VOTRE CODE ICI


## Exercice 6 : Concaténation et empilement (2D)

**Objectif :**
Soit deux matrices $A$ et $B$ de dimensions $3 \times 2$.
1. Empilez-les verticalement pour obtenir une matrice $6 \times 2$.
2. Empilez-les horizontalement pour obtenir une matrice $3 \times 4$.

In [ ]:
# VOTRE CODE ICI


## Exercice 7 : Recherche d'indices spécifiques (`np.where`) (1D)

**Objectif :**
Soit un vecteur 1D de 12 valeurs réelles. Récupérez les **indices** (et non les valeurs) de tous les éléments compris entre 10 et 20 inclus.

In [ ]:
# VOTRE CODE ICI


## Exercice 8 : Calcul de la diagonale et trace (2D)

**Objectif :**
Générez une matrice carrée $4 \times 4$ d'entiers.
1. Extrayez les éléments de la diagonale principale sous forme de vecteur 1D.
2. Calculez la somme de ces éléments (la trace) en utilisant la fonction NumPy dédiée.

In [ ]:
# VOTRE CODE ICI


## Exercice 9 : Masquage conditionnel & Remplacement rapide (1D)

**Objectif :**
Créez un vecteur 1D de 20 entiers aléatoires entre -10 et 10. Sans utiliser de boucle for ni d'instructions if, remplacez tous les nombres négatifs impairs par leur carré, et tous les nombres positifs pairs par 0.

In [ ]:
# VOTRE CODE ICI


## Exercice 10 : Extraction par glissement / Fenêtres glissantes (1D)

**Objectif :**
Soit un vecteur 1D $V = [1, 2, 3, 4, 5, 6, 7, 8]$. Générez une matrice 2D représentant toutes les sous-fenêtres glissantes de taille 3 avec un pas (stride) de 1.Résultat attendu :$$\begin{bmatrix} 1 & 2 & 3 \\ 2 & 3 & 4 \\ 3 & 4 & 5 \\ \dots & \dots & \dots \end{bmatrix}$$

In [ ]:
# VOTRE CODE ICI


## Exercice 11 : Extraction des k plus grands éléments par ligne (2D)

**Objectif :**
Soit une matrice 2D de dimensions $6 \times 8$ remplie d'entiers aléatoires. Extrayez, pour chaque ligne, les 3 plus grandes valeurs et leurs indices respectifs, triés par ordre décroissant.

In [ ]:
# VOTRE CODE ICI